/** Declaration file generated by dts-gen */

export = bunyan_slack;

interface BunyanSlackOptions {
	webhook_url: string;
	channel: string;
	username: string;
	icon_emoji?: string;
	customFormatter?: (record: {msg: string}, levelName: string) => void;
	fetch?: (options: any) => Promise<any>;
}

type ErrorHandler = (err: Error) => void;

declare class bunyan_slack {
	constructor(options: BunyanSlackOptions, error?: ErrorHandler);

	write(record: string | {level: string; msg: string}): any;
}
